// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/trace_tap component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("trace_tap")
	ScopeName = "go.opentelemetry.io/collector/extension/tracetapextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
